#!/usr/bin/env python
import sys
import re

from find_hierosoft import hierosoft
# ^ works for submodules since changes path

from hierosoft.checkversion import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
