#!/usr/bin/env python3
import os
import sys

import PIL.ExifTags

SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPTS_DIR)
if os.path.isfile(os.path.join(REPO_DIR, "hierosoft", "__init__.py")):
    sys.path.insert(0, REPO_DIR)  # Allow importing hierosoft from here


from hierosoft.moremeta import (  # noqa E402
    # modificationDate,
    # metaBySize,
    # minBannerRatio,
    # isPhotoSize,
    # isThumbnailSize,
    extract_exif_date,
)


def show_meta(path):
    dt = extract_exif_date(path, verbose=True)
    print(dt)


def main():
    paths = []
    for argi, arg in enumerate(sys.argv):
        if argi == 0:
            continue
        paths.append(arg)

    for path in paths:
        show_meta(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
