# -*- coding: utf-8 -*-
"""
Do not edit. This file is generated by hierosoftrepo.py via prebuild.
These files are packed for the binary version.
"""
import base64
import zlib


# hierosoft_svg is TM Hierosoft LLC, USA:
hierosoft_svg = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">

<svg xmlns="http://www.w3.org/2000/svg"
     width="0.333333in" height="0.333333in"
     viewBox="0 0 200 200">
  <path id="Selection #1"
        fill="black" stroke="none" stroke-width="0"
        d="M 66.41,9.83
           C 63.94,10.41 62.07,11.52 60.74,12.92
             59.42,14.32 58.63,16.02 58.32,17.77
             58.01,19.52 58.18,21.32 58.77,22.95
             59.36,24.57 60.36,26.02 61.73,27.04
             62.74,27.79 63.74,28.24 64.73,28.52
             65.72,28.81 66.70,28.93 67.65,29.04
             68.61,29.15 69.54,29.24 70.44,29.46
             71.34,29.69 72.21,30.04 73.05,30.68
             73.65,31.13 74.23,31.63 74.74,32.16
             75.24,32.70 75.67,33.26 75.95,33.87
             76.24,34.47 76.39,35.11 76.34,35.78
             76.29,36.45 76.03,37.16 75.52,37.89
             75.15,38.43 74.63,38.98 74.03,39.53
             73.43,40.07 72.74,40.62 72.03,41.14
             71.32,41.65 70.59,42.15 69.89,42.62
             69.19,43.08 68.53,43.51 67.97,43.88
             67.97,43.88 63.87,46.57 63.87,46.57
             63.87,46.57 59.77,49.26 59.77,49.26
             59.77,49.26 55.66,51.95 55.66,51.95
             55.66,51.95 51.56,54.64 51.56,54.64
             51.56,54.64 50.10,55.69 50.10,55.69
             50.10,55.69 48.63,56.74 48.63,56.74
             48.63,56.74 47.17,57.80 47.17,57.80
             47.17,57.80 45.70,58.85 45.70,58.85
             45.49,59.01 45.26,59.20 45.01,59.40
             44.76,59.60 44.49,59.80 44.22,59.99
             43.95,60.18 43.67,60.36 43.39,60.49
             43.12,60.63 42.84,60.72 42.58,60.75
             42.36,60.78 42.00,60.72 41.56,60.61
             41.13,60.50 40.62,60.34 40.10,60.17
             39.59,59.99 39.07,59.80 38.61,59.64
             38.16,59.47 37.76,59.33 37.50,59.24
             36.85,59.03 36.11,58.82 35.32,58.62
             34.53,58.41 33.70,58.23 32.86,58.06
             32.02,57.89 31.17,57.75 30.37,57.64
             29.57,57.53 28.80,57.46 28.12,57.43
             26.41,57.37 24.59,57.56 22.85,58.01
             21.10,58.46 19.42,59.17 17.99,60.14
             16.56,61.11 15.37,62.35 14.61,63.85
             13.84,65.35 13.50,67.11 13.75,69.14
             13.89,70.30 14.28,71.37 14.84,72.33
             15.40,73.30 16.13,74.18 16.97,74.97
             17.80,75.76 18.74,76.46 19.71,77.09
             20.68,77.72 21.69,78.28 22.66,78.76
             23.07,78.96 23.60,79.17 24.18,79.40
             24.76,79.63 25.39,79.88 25.98,80.16
             26.56,80.45 27.11,80.77 27.53,81.14
             27.96,81.52 28.26,81.94 28.36,82.43
             28.36,82.43 28.12,84.48 28.12,84.48
             28.12,84.48 27.88,86.53 27.88,86.53
             27.88,86.53 27.64,88.58 27.64,88.58
             27.64,88.58 27.40,90.62 27.40,90.62
             27.40,90.62 27.29,94.73 27.29,94.73
             27.29,94.73 27.18,98.83 27.18,98.83
             27.18,98.83 27.07,102.93 27.07,102.93
             27.07,102.93 26.95,107.03 26.95,107.03
             26.95,107.03 27.04,108.20 27.04,108.20
             27.04,108.20 27.13,109.37 27.13,109.37
             27.13,109.37 27.22,110.55 27.22,110.55
             27.22,110.55 27.31,111.72 27.31,111.72
             27.66,116.81 28.38,121.86 29.44,126.86
             30.49,131.85 31.88,136.78 33.56,141.62
             35.24,146.45 37.21,151.18 39.45,155.78
             41.68,160.38 44.18,164.84 46.90,169.14
             46.90,169.14 49.64,173.05 49.64,173.05
             49.64,173.05 52.38,176.95 52.38,176.95
             52.38,176.95 55.12,180.86 55.12,180.86
             55.12,180.86 57.86,184.77 57.86,184.77
             58.07,185.04 58.38,185.48 58.75,185.99
             59.11,186.50 59.53,187.08 59.96,187.63
             60.38,188.19 60.82,188.73 61.21,189.15
             61.61,189.58 61.96,189.90 62.23,190.01
             62.39,190.08 62.59,190.13 62.81,190.17
             63.03,190.20 63.27,190.22 63.51,190.23
             63.75,190.24 64.00,190.24 64.23,190.24
             64.45,190.24 64.67,190.23 64.84,190.23
             64.84,190.23 82.42,190.23 82.42,190.23
             82.42,190.23 100.00,190.23 100.00,190.23
             100.00,190.23 117.58,190.23 117.58,190.23
             117.58,190.23 135.16,190.23 135.16,190.23
             136.04,190.23 136.67,190.22 137.17,190.14
             137.67,190.06 138.04,189.90 138.41,189.60
             138.77,189.30 139.13,188.85 139.61,188.20
             140.09,187.55 140.70,186.69 141.55,185.55
             141.55,185.55 143.80,182.42 143.80,182.42
             143.80,182.42 146.04,179.30 146.04,179.30
             146.04,179.30 148.28,176.17 148.28,176.17
             148.28,176.17 150.52,173.05 150.52,173.05
             153.58,168.46 156.40,163.72 158.93,158.84
             161.46,153.96 163.70,148.94 165.61,143.80
             167.52,138.66 169.10,133.40 170.30,128.05
             171.49,122.70 172.31,117.25 172.69,111.72
             172.69,111.72 172.78,110.74 172.78,110.74
             172.78,110.74 172.87,109.77 172.87,109.77
             172.87,109.77 172.96,108.79 172.96,108.79
             172.96,108.79 173.05,107.81 173.05,107.81
             173.06,106.29 173.09,104.76 173.10,103.22
             173.11,101.69 173.11,100.15 173.08,98.61
             173.05,97.07 172.99,95.54 172.89,94.01
             172.79,92.48 172.64,90.96 172.44,89.45
             172.44,89.45 172.23,87.99 172.23,87.99
             172.23,87.99 172.02,86.52 172.02,86.52
             172.02,86.52 171.81,85.06 171.81,85.06
             171.81,85.06 171.61,83.59 171.61,83.59
             171.58,83.39 171.55,83.14 171.51,82.88
             171.47,82.62 171.44,82.34 171.41,82.06
             171.39,81.78 171.39,81.51 171.42,81.25
             171.44,81.00 171.50,80.77 171.61,80.58
             171.72,80.33 172.04,80.06 172.47,79.78
             172.90,79.50 173.44,79.22 174.01,78.95
             174.57,78.68 175.16,78.43 175.68,78.20
             176.20,77.98 176.66,77.78 176.95,77.64
             178.27,76.98 179.65,76.20 180.93,75.30
             182.21,74.39 183.39,73.36 184.33,72.20
             185.27,71.03 185.96,69.74 186.25,68.32
             186.54,66.90 186.42,65.35 185.75,63.67
             184.89,61.49 183.54,59.88 181.89,58.74
             180.24,57.60 178.29,56.91 176.22,56.57
             174.14,56.22 171.94,56.21 169.79,56.42
             167.64,56.64 165.54,57.07 163.67,57.59
             163.31,57.69 162.73,57.90 162.04,58.15
             161.35,58.40 160.56,58.70 159.78,58.97
             159.00,59.25 158.24,59.50 157.61,59.68
             156.99,59.86 156.49,59.96 156.25,59.91
             156.02,59.87 155.76,59.77 155.48,59.62
             155.21,59.48 154.92,59.29 154.63,59.09
             154.35,58.90 154.07,58.69 153.81,58.49
             153.56,58.29 153.32,58.11 153.12,57.96
             153.12,57.96 151.76,56.99 151.76,56.99
             151.76,56.99 150.39,56.01 150.39,56.01
             150.39,56.01 149.02,55.04 149.02,55.04
             149.02,55.04 147.66,54.06 147.66,54.06
             147.66,54.06 143.75,51.52 143.75,51.52
             143.75,51.52 139.84,48.97 139.84,48.97
             139.84,48.97 135.94,46.43 135.94,46.43
             135.94,46.43 132.03,43.88 132.03,43.88
             131.47,43.51 130.81,43.08 130.11,42.62
             129.41,42.15 128.68,41.65 127.97,41.14
             127.26,40.62 126.57,40.07 125.97,39.53
             125.37,38.98 124.85,38.43 124.48,37.89
             123.91,37.07 123.69,36.23 123.73,35.41
             123.76,34.59 124.06,33.80 124.52,33.06
             124.98,32.33 125.60,31.65 126.30,31.08
             127.00,30.51 127.77,30.05 128.52,29.72
             128.52,29.72 130.27,29.41 130.27,29.41
             130.27,29.41 132.03,29.10 132.03,29.10
             132.03,29.10 133.79,28.78 133.79,28.78
             133.79,28.78 135.55,28.47 135.55,28.47
             136.78,28.04 137.85,27.41 138.74,26.62
             139.63,25.83 140.33,24.88 140.85,23.84
             141.36,22.79 141.67,21.65 141.77,20.46
             141.88,19.26 141.77,18.03 141.43,16.80
             141.06,15.45 140.51,14.34 139.81,13.43
             139.11,12.52 138.26,11.81 137.30,11.27
             136.34,10.73 135.26,10.37 134.11,10.14
             132.96,9.91 131.74,9.81 130.47,9.83
             130.47,9.83 119.92,9.83 119.92,9.83
             119.92,9.83 109.37,9.83 109.37,9.83
             109.37,9.83 98.83,9.83 98.83,9.83
             98.83,9.83 88.28,9.83 88.28,9.83
             88.28,9.83 82.81,9.83 82.81,9.83
             82.81,9.83 77.34,9.83 77.34,9.83
             77.34,9.83 71.87,9.83 71.87,9.83
             71.87,9.83 66.41,9.83 66.41,9.83 Z" />
  <path id="path362"
        fill="white" stroke="none" stroke-width="0"
        d="M 71.09,51.16
           C 71.18,51.65 71.08,52.40 70.87,53.27
             70.66,54.14 70.33,55.15 69.97,56.16
             69.61,57.17 69.22,58.19 68.86,59.09
             68.51,59.99 68.19,60.78 67.99,61.32
             67.32,63.15 66.55,65.25 65.73,67.47
             64.92,69.70 64.06,72.05 63.25,74.41
             62.43,76.77 61.65,79.13 60.98,81.35
             60.31,83.57 59.75,85.66 59.38,87.49
             59.17,88.51 58.94,89.49 58.76,90.46
             58.58,91.42 58.45,92.36 58.43,93.29
             58.41,94.22 58.49,95.14 58.75,96.06
             59.00,96.98 59.43,97.89 60.08,98.82
             60.94,100.03 62.06,101.02 63.33,101.82
             64.61,102.63 66.05,103.25 67.55,103.75
             69.06,104.25 70.62,104.62 72.16,104.92
             73.69,105.21 75.19,105.44 76.56,105.63
             78.41,105.90 80.29,106.07 82.17,106.18
             84.06,106.28 85.96,106.33 87.86,106.34
             89.76,106.35 91.67,106.32 93.57,106.30
             95.46,106.27 97.35,106.24 99.22,106.24
             101.40,106.24 103.59,106.27 105.77,106.28
             107.96,106.30 110.15,106.31 112.33,106.28
             114.52,106.25 116.70,106.19 118.88,106.05
             121.06,105.92 123.23,105.72 125.39,105.41
             127.21,105.16 129.16,104.82 131.05,104.31
             132.95,103.80 134.79,103.12 136.40,102.20
             138.01,101.27 139.38,100.09 140.34,98.58
             141.30,97.07 141.85,95.22 141.80,92.96
             141.78,92.17 141.69,91.31 141.55,90.42
             141.41,89.52 141.22,88.59 141.01,87.66
             140.80,86.73 140.56,85.80 140.32,84.91
             140.08,84.03 139.84,83.18 139.62,82.41
             139.62,82.41 137.66,76.75 137.66,76.75
             137.66,76.75 135.69,71.09 135.69,71.09
             135.69,71.09 133.73,65.42 133.73,65.42
             133.73,65.42 131.76,59.76 131.76,59.76
             131.76,59.76 131.05,57.71 131.05,57.71
             131.05,57.71 130.33,55.66 130.33,55.66
             130.33,55.66 129.62,53.60 129.62,53.60
             129.62,53.60 128.91,51.55 128.91,51.55
             129.55,51.84 130.41,52.31 131.39,52.89
             132.37,53.47 133.46,54.15 134.55,54.84
             135.64,55.54 136.73,56.26 137.72,56.91
             138.70,57.56 139.58,58.15 140.23,58.59
             141.99,59.75 144.01,61.11 146.12,62.61
             148.23,64.11 150.43,65.74 152.52,67.47
             154.61,69.20 156.61,71.01 158.31,72.87
             160.01,74.73 161.42,76.62 162.35,78.51
             162.62,79.03 162.84,79.64 163.02,80.28
             163.21,80.93 163.37,81.62 163.50,82.32
             163.64,83.01 163.75,83.72 163.85,84.40
             163.94,85.08 164.03,85.73 164.11,86.32
             164.11,86.32 164.39,89.35 164.39,89.35
             164.39,89.35 164.67,92.37 164.67,92.37
             164.67,92.37 164.95,95.40 164.95,95.40
             164.95,95.40 165.23,98.43 165.23,98.43
             165.23,98.43 165.23,100.38 165.23,100.38
             165.23,100.38 165.23,102.34 165.23,102.34
             165.23,102.34 165.23,104.29 165.23,104.29
             165.23,104.29 165.23,106.24 165.23,106.24
             165.23,106.24 165.15,107.41 165.15,107.41
             165.15,107.41 165.06,108.59 165.06,108.59
             165.06,108.59 164.97,109.76 164.97,109.76
             164.97,109.76 164.88,110.93 164.88,110.93
             164.66,114.07 164.29,117.19 163.78,120.28
             163.28,123.37 162.63,126.44 161.86,129.47
             161.08,132.51 160.18,135.51 159.16,138.47
             158.14,141.44 157.00,144.37 155.75,147.26
             154.71,149.67 153.59,152.05 152.39,154.41
             151.20,156.76 149.93,159.09 148.59,161.37
             147.26,163.66 145.86,165.91 144.41,168.12
             142.95,170.33 141.45,172.49 139.89,174.60
             139.63,174.95 139.20,175.55 138.69,176.26
             138.17,176.97 137.57,177.79 136.96,178.59
             136.35,179.39 135.74,180.16 135.20,180.77
             134.67,181.39 134.22,181.85 133.92,182.01
             133.71,182.13 133.47,182.22 133.22,182.28
             132.96,182.34 132.70,182.37 132.43,182.39
             132.16,182.41 131.89,182.42 131.62,182.42
             131.36,182.42 131.10,182.41 130.86,182.41
             130.86,182.41 129.30,182.41 129.30,182.41
             129.30,182.41 127.73,182.41 127.73,182.41
             127.73,182.41 126.17,182.41 126.17,182.41
             126.17,182.41 124.61,182.41 124.61,182.41
             124.71,181.77 124.87,181.09 125.06,180.41
             125.26,179.72 125.49,179.01 125.74,178.31
             125.99,177.61 126.25,176.90 126.51,176.21
             126.76,175.53 127.01,174.85 127.22,174.21
             127.22,174.21 128.91,169.13 128.91,169.13
             128.91,169.13 130.60,164.05 130.60,164.05
             130.60,164.05 132.29,158.98 132.29,158.98
             132.29,158.98 133.98,153.90 133.98,153.90
             134.22,153.09 134.48,152.16 134.74,151.17
             135.00,150.17 135.26,149.12 135.49,148.06
             135.72,147.00 135.93,145.94 136.08,144.94
             136.22,143.94 136.32,143.00 136.33,142.18
             136.33,142.18 136.33,141.69 136.33,141.69
             136.33,141.69 136.33,141.20 136.33,141.20
             136.33,141.20 136.33,140.71 136.33,140.71
             136.33,140.71 136.33,140.23 136.33,140.23
             136.33,139.78 136.33,139.39 136.32,139.04
             136.32,138.69 136.31,138.38 136.28,138.06
             136.25,137.75 136.20,137.43 136.12,137.09
             136.05,136.74 135.95,136.37 135.80,135.93
             135.03,133.54 133.82,131.67 132.31,130.21
             130.80,128.74 128.98,127.67 127.00,126.89
             125.01,126.10 122.85,125.60 120.65,125.25
             118.46,124.90 116.21,124.71 114.06,124.56
             114.06,124.56 113.09,124.48 113.09,124.48
             113.09,124.48 112.11,124.39 112.11,124.39
             112.11,124.39 111.13,124.30 111.13,124.30
             111.13,124.30 110.16,124.21 110.16,124.21
             110.16,124.21 107.52,124.21 107.52,124.21
             107.52,124.21 104.88,124.21 104.88,124.21
             104.88,124.21 102.25,124.21 102.25,124.21
             102.25,124.21 99.61,124.21 99.61,124.21
             99.61,124.21 97.46,124.21 97.46,124.21
             97.46,124.21 95.31,124.21 95.31,124.21
             95.31,124.21 93.16,124.21 93.16,124.21
             93.16,124.21 91.02,124.21 91.02,124.21
             91.02,124.21 89.84,124.30 89.84,124.30
             89.84,124.30 88.67,124.39 88.67,124.39
             88.67,124.39 87.50,124.48 87.50,124.48
             87.50,124.48 86.33,124.56 86.33,124.56
             84.72,124.68 83.01,124.81 81.29,125.02
             79.56,125.23 77.82,125.52 76.13,125.96
             74.44,126.39 72.81,126.98 71.32,127.78
             69.82,128.57 68.46,129.58 67.31,130.86
             66.24,132.06 65.47,133.37 64.94,134.75
             64.42,136.12 64.13,137.57 64.01,139.06
             63.90,140.54 63.95,142.05 64.11,143.56
             64.28,145.07 64.54,146.58 64.84,148.04
             65.21,149.80 65.72,151.79 66.31,153.88
             66.91,155.97 67.59,158.17 68.31,160.37
             69.02,162.57 69.77,164.77 70.49,166.85
             71.21,168.93 71.91,170.90 72.53,172.65
             72.53,172.65 73.35,175.09 73.35,175.09
             73.35,175.09 74.16,177.53 74.16,177.53
             74.16,177.53 74.97,179.97 74.97,179.97
             74.97,179.97 75.78,182.41 75.78,182.41
             75.78,182.41 74.12,182.41 74.12,182.41
             74.12,182.41 72.46,182.41 72.46,182.41
             72.46,182.41 70.80,182.41 70.80,182.41
             70.80,182.41 69.14,182.41 69.14,182.41
             68.04,182.41 67.19,182.28 66.51,182.04
             65.82,181.80 65.29,181.44 64.82,180.97
             64.35,180.50 63.93,179.93 63.47,179.25
             63.02,178.58 62.51,177.81 61.87,176.94
             60.90,175.66 59.95,174.36 59.02,173.05
             58.10,171.74 57.18,170.42 56.29,169.09
             55.40,167.75 54.53,166.41 53.67,165.05
             52.82,163.69 51.99,162.32 51.17,160.93
             48.94,157.13 46.90,153.20 45.07,149.18
             43.24,145.16 41.63,141.04 40.26,136.84
             38.89,132.64 37.76,128.37 36.89,124.04
             36.03,119.72 35.43,115.34 35.12,110.93
             35.12,110.93 35.03,109.76 35.03,109.76
             35.03,109.76 34.94,108.59 34.94,108.59
             34.94,108.59 34.85,107.41 34.85,107.41
             34.85,107.41 34.77,106.24 34.77,106.24
             34.77,106.24 34.77,104.00 34.77,104.00
             34.77,104.00 34.77,101.75 34.77,101.75
             34.77,101.75 34.77,99.50 34.77,99.50
             34.77,99.50 34.77,97.26 34.77,97.26
             34.77,97.26 35.05,94.52 35.05,94.52
             35.05,94.52 35.33,91.79 35.33,91.79
             35.33,91.79 35.61,89.05 35.61,89.05
             35.61,89.05 35.89,86.32 35.89,86.32
             35.96,85.79 36.04,85.18 36.14,84.53
             36.23,83.88 36.34,83.20 36.47,82.52
             36.59,81.85 36.73,81.18 36.90,80.56
             37.06,79.94 37.25,79.37 37.46,78.90
             37.94,77.84 38.57,76.79 39.30,75.77
             40.03,74.75 40.87,73.75 41.76,72.79
             42.64,71.83 43.58,70.91 44.52,70.06
             45.45,69.20 46.39,68.39 47.27,67.67
             48.50,66.65 49.75,65.66 51.03,64.69
             52.31,63.73 53.60,62.78 54.91,61.86
             56.22,60.93 57.55,60.03 58.88,59.14
             60.21,58.25 61.55,57.37 62.89,56.51
             62.89,56.51 64.94,55.17 64.94,55.17
             64.94,55.17 66.99,53.84 66.99,53.84
             66.99,53.84 69.04,52.50 69.04,52.50
             69.04,52.50 71.09,51.16 71.09,51.16 Z" />
</svg>
"""

# this version's sources.json (update is downloaded unless --offline):
sources_json = """{
  "sources_urls": [
    "https://github.com/Hierosoft/hierosoft/blob/main/hierosoft/assets/data/sources.json"
  ],
  "sources_urls.comment": "If GitHub sources_urls is down, try https://minetest.io/launcherapi/sources.json",
  "news": [
    {
      "date": "2024-02-10 15:03",
      "text": "Launcher GUI development has resumed!",
      "url": "https://minetest.io"
    }
  ],
  "programs": {
    "hierosoft": {
      "sources": [
        {
          "base_url": "https://minetest.io",
          "bin_names": [
            "run.pyw"
          ],
          "html_url": "https://minetest.io/downloads/launcher.php",
          "must_contain": "/Hierosoft/hierosoft/archive/refs/heads/main.zip",
          "title": "Hierosoft Launcher",
          "version": "current"
        }
      ]
    },
    "blender-nightly": {
      "sources": [
        {
          "title": "Blender Nightly",
          "version": "3.6.3",
          "version.comment": "# ^ formerly  parser.release_version",
          "platforms": {
              "Linux": "linux",
              "Windows": "windows",
              "Darwin": "macos"
          },
          "architectures": {
              "Linux": ["x86_64", "x64"],
              "Windows": "x64",
              "Darwin.x64": ["x64"],
              "Darwin.arm64": ["arm64"],
              "Darwin.comment": "x64, but if 'arm64' in platform.platform() such as macOS-12.0.1-arm64-i386-64bit as seen at <https://stackoverflow.com/a/70253434/4541104> then arm64"
          },
          "must_contain": "/blender-",
          "must_contain.comment": "# ^ formerly  /download//blender-*",
          "html_url": "https://builder.blender.org/download/",
          "bin_names": ["blender", "blender.exe"]
        },
        {
          "title": "Blender Nightly",
          "version": "4.0.0",
          "version.comment": "# ^ formerly  parser.release_version",
          "platforms": {
              "Linux": "linux",
              "Windows": "windows",
              "Darwin": "macos"
          },
          "architectures": {
              "Linux": ["x86_64", "x64"],
              "Windows": "x64",
              "Darwin.x64": ["x64"],
              "Darwin.arm64": ["arm64"],
              "Darwin.comment": "x64, but if 'arm64' in platform.platform() then arm64 such as macOS-12.0.1-arm64-i386-64bit as seen at <https://stackoverflow.com/a/70253434/4541104>"
          },
          "must_contain": "/blender-",
          "must_contain.comment": "# ^ formerly  /download//blender-*",
          "html_url": "https://builder.blender.org/download/",
          "bin_names": ["blender", "blender.exe"]
        }
      ]
    }
  }
}"""
transparent_png_str = (
    "eJwBFgLp/YlQTkcNChoKAAAADUlIRFIAAAAQAAAAEAgGAAAAH/P/YQAAAYVpQ0NQSUNDIHByb"
    "2ZpbGUAACiRfZE9SMNAGIbfpoo/VBzaQcQhQnXRLiriWKpYBAulrdCqg8mlf9CkIUlxcRRcCw"
    "7+LFYdXJx1dXAVBMEfEFcXJ0UXKfG7pNAixjuOe3jve1/uvgOERoWpZlcUUDXLSMVjYja3Kva"
    "8oo9mEBMYlZipJ9KLGXiOr3v4+H4X4VnedX+OASVvMsAnEkeZbljEG8Szm5bOeZ84xEqSQnxO"
    "PGnQBYkfuS67/Ma56LDAM0NGJjVPHCIWix0sdzArGSrxDHFYUTXKF7IuK5y3OKuVGmvdk78wk"
    "NdW0lynNYI4lpBAEiJk1FBGBRYitGukmEjReczDP+z4k+SSyVUGI8cCqlAhOX7wP/jdW7MwPe"
    "UmBWJA94ttf4wBPbtAs27b38e23TwB/M/Aldb2VxvA3Cfp9bYWPgIGt4GL67Ym7wGXO8DQky4"
    "ZkiP5aQmFAvB+Rt+UA4K3QP+a27fWOU4fgAz1avkGODgExouUve7x7t7Ovv1b0+rfD9WCcs4U"
    "0+VzAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAACxKAAAsSgF3enRNAAAAB3RJTUUH5wkMD"
    "TEn69x92QAAABJJREFUOMtjYBgFo2AUjAIIAAAEEAABhT+qcgAAAABJRU5ErkJggsAz2b4="
)
transparent_png = zlib.decompress(base64.b64decode(
    transparent_png_str.encode('utf-8')
))
white_png_str = (
    "eJwBIgLd/YlQTkcNChoKAAAADUlIRFIAAAAQAAAAEAgGAAAAH/P/YQAAAYVpQ0NQSUNDIHByb"
    "2ZpbGUAACiRfZE9SMNAGIbfpoo/VBzaQcQhQnXRLiriWKpYBAulrdCqg8mlf9CkIUlxcRRcCw"
    "7+LFYdXJx1dXAVBMEfEFcXJ0UXKfG7pNAixjuOe3jve1/uvgOERoWpZlcUUDXLSMVjYja3Kva"
    "8oo9mEBMYlZipJ9KLGXiOr3v4+H4X4VnedX+OASVvMsAnEkeZbljEG8Szm5bOeZ84xEqSQnxO"
    "PGnQBYkfuS67/Ma56LDAM0NGJjVPHCIWix0sdzArGSrxDHFYUTXKF7IuK5y3OKuVGmvdk78wk"
    "NdW0lynNYI4lpBAEiJk1FBGBRYitGukmEjReczDP+z4k+SSyVUGI8cCqlAhOX7wP/jdW7MwPe"
    "UmBWJA94ttf4wBPbtAs27b38e23TwB/M/Aldb2VxvA3Cfp9bYWPgIGt4GL67Ym7wGXO8DQky4"
    "ZkiP5aQmFAvB+Rt+UA4K3QP+a27fWOU4fgAz1avkGODgExouUve7x7t7Ovv1b0+rfD9WCcs4U"
    "0+VzAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAACxKAAAsSgF3enRNAAAAB3RJTUUH5wkMD"
    "TESvW+5+gAAAB5JREFUOMtj/P///38GCgATA4Vg1IBRA0YNGCwGAABrygQc+9ibxwAAAABJRU"
    "5ErkJggmLU3ow="
)
white_png = zlib.decompress(base64.b64decode(
    white_png_str.encode('utf-8')
))
hierosoft_16px_png_str = (
    "eJwBJQLa/YlQTkcNChoKAAAADUlIRFIAAAAQAAAAEAgGAAAAH/P/YQAAAAlwSFlzAAAHYQAAB"
    "2EBlcO4tgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAGySURBVDiNfZ"
    "M/ixpRFMV/z3WfWonmA2wh/kFYk8ZCEggJMdgGbQzihwiC/VhuoyRfw0I/QtKmikvEwi1Ey0w"
    "hDDohclJEjZmZzYXbnHfuee+ee5+RRDCMMbeADcC/gG8KFkj6J4E3gB7JtyF+hIAF3gP7i8L9"
    "EbsO8mOh90MMeBpowR6xqxD7eOszoAPUK5XKstPphJ7farVUqVQegHfAB+D1uQVgdiJ5nqdar"
    "RYSqFar8jxPzWbzhH29FMhlMpmH/X6v1WolY0ykicvlUrvdTtls9jvw5OyBpGWpVPqZSCSYz+"
    "dEjRZgsViQTCbJ5/NXkn4AxE+H8Xj8GqBerzOdTpnNZmy3WwDS6TTlcplGo/HHUWv/GnwaRy6"
    "X+6KLOBwOcl1XruvqcDhcHimfz38O7QFwt16vJUn9fl/W2nPv1lr1ej1J0mazEXAXJfBiOBxK"
    "korFYsjAm5sbSdJoNBLwPHITC4XCve/76na7IYF2uy3f91UqlWaPrjLwynEcTSaTkMB4PJbjO"
    "AJe/vcvpFKpj4PBQLFY7FxsjJHjOEqlUp+CfBOcuTHGAreRiwD3kvxL4DeVJZif8fSmbQAAAA"
    "BJRU5ErkJggshn98I="
)
hierosoft_16px_png = zlib.decompress(base64.b64decode(
    hierosoft_16px_png_str.encode('utf-8')
))
hierosoft_48px_png_str = (
    "eJwB5wQY+4lQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAFzUkdCAdnJLH8AA"
    "AAEZ0FNQQAAsY8L/GEFAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJ"
    "y6UTwAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAAHYYAAB2GAV2iE4EAAAAHdElNRQfqAQI"
    "DISxQY7QmAAAEK0lEQVRo3u2Z3W9URRjGf27dlSoSC1QuqlXAGmJBwKY2NiERjEgiJPiRcEMo"
    "4cJw5603BC6I4Q6aYKomVWP8C/DCyAUiJSQ0iJiILS1CDEIlsEA/2C3sR7nos8nJyZmzPTPTL"
    "iZ9k5PZnDkz7zwz78cz78K81FaecBibAj4B3nGYIw+cBL4DynMN/gegKMUuT1Fzzak8DVwBpj"
    "w9fwP1tmZgI5PAqMcNuQs8mOtTWAGcAa4COYtdz2nsaaC5lkFgEfAhMJZg8WPAduBZx0DiVX5"
    "OAODE4xaK3wAmEgCY0Jia7/4CYD8wbuED4xq7oFaLfxP4Eyg4hM8CcBHomMuF1wMHFUVGgeMK"
    "g0kXPwH0a44ccEj5xYs0AK8ALwDpwPs2KZ0CzgKdQDuQtQTwvuY4q3e/6WSR3lZFq53A5pkAf"
    "BLoAf4BbgEjwCDwrd5nxV8OBjLnPlECGxPqliPX6wTyOs1TMs+sElxJfb8rbBuly6CowluuAe"
    "8Fvn8KuODgA8MhCrFVOuLG7IsDcCRmYL9MKiitHnhQW2jOZuB8zPcH4gCsMsTzQWBxxPe9HgB"
    "EMdElwKUIKzhfzYQANgB/BPjNJLDa4C9jHgBMAJmI+ddI9xRwAziahLFmgL0afM7wzUY5lyuA"
    "ErDDoOOccsXrSen0Q+CYfp80fLPbExVIAXsMfb/qpEds7gNNagcM/Ge9Ry7zcijfVGRY7Ys2A"
    "BrUXonoS3vmMGkDgKtqX7IBUMl6Nw0m1u/pIl5W0spF9I2ENjMyksRxHmIW2QX8C3wMPAc8o8"
    "RWzaxKcsw8cE/3iE8N3xbU1tkAyFQZXAI+U2JZrgS0TMArIKZCv8vAfVGE6zLPXMwa6qpsYiy"
    "AO2obZ3DBHzA4u6ssVXvbxgeuBbJzraQl5MyJAFQcaF0NAbwWWksiE6rY6tqE9+M0sDAizBZE"
    "PR7KH2YinaL1OdvYfEbRopqzfyAOP6qFxj3jqkrsVNSKc+C86kZp22pDt6JNRwzIHx140C8xI"
    "NZK92GXjP+Rokx3DKFzJXO7DXMfle7tLk60TFR20HCMBzwA+N5wsn8pEja6FHdv6m7QBLwV0Z"
    "/3EGnuR7xr1+1vQE7sJJ1M1/B7ImzRhwntivC9L6XzbV+lwyFVC56PYKyTDosvR9yzG6Vr2Gf"
    "pcZsUfmMItbYALkREoS/Ut8VnRswAfbL5llDffgcAn4d2eaWSVp/hnuwk78rh+kIMtV0JzKa4"
    "uyGUuPp0yd80G7wkBfykU+gKmdGgBYDLIbqxS3Mfm82y+2Lxo/9CDn04YXmxHIr/jZrzXoBCz"
    "5psFqc5HTCllQnL7MUASawTjyqotDjrkgK+Ek/pFd1en9APJlWFblXhuAR8jf2/pollkXJDUT"
    "H7tnZwpn9ulzQmqzmGmP7DzypJ2cqrKrO7OlxZFech5uV/KI8A/teefrn/TrsAAAAASUVORK5"
    "CYIJDCyWo"
)
hierosoft_48px_png = zlib.decompress(base64.b64decode(
    hierosoft_48px_png_str.encode('utf-8')
))
icon_app_empty_png_str = (
    "eJwBEwPs/IlQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxQvOLozbHEAAAKgSURBVGje7Z"
    "pNaBVXFMd/J9F8NMZ8WC2NBTELcaOUWnCvLnUjRLIqFrRQabeCorgSzbIIXSjSvdJNiyjippT"
    "iRhciVRQSddHYhsamxmgSjb8uvE8fw32uAn3zmP/mDPOfM3POvXM+uPdCyRHFG2ob0AF0Z55/"
    "GhFLan9G91VEzKodQE9Gdy4iFtVeYEWBex0R/6rtwOqM7ouImH+vJ+oa9Wf1iHrcPD5Nz05lu"
    "F8SN9pAdyTxv2W4ycRta6B7NPEH1R/TAEJhJM4Du4Fh4AxwM+Pn8yRvAQMF7n6STxro/pPkPa"
    "CzwP1d9/6c7uP0Z3wLbAFeAqP1o9+jLql/pSluSqj96rS6oHYCtCVuIF1PRMRs0wZsxAzwMMV"
    "oX70DpUUtBuaAs8CDEth8DRgHFmgZqH3qafVQCWzdq36ldtff/CTl2+slcOBmsnVdSwRx5UDl"
    "wDLVgSng81QPmh2HgF5gpqXqwJD6RL1aAlt/UsfVNfUx0JYaut4SjPf61PK3V1mocmAZ0+h8a"
    "lPvlsDmP4B+YKml0mi3OqLuKIGt29VdafmmaqerLFQ50Cp1YBrYl2Sz4yTwITBLy0Bdp95Qfy"
    "iBrWPqBbWvqgNVFqoceOfAK2ACmKTC/xPZHWmDbXMJbF2vDqcdzSqNVllouaZlVdpm/VP9oMn"
    "tnFYX1a633WhEPFMvAXuAA+o54NfMOy5FxAl1P/BNhv8iIu6ol4G1Be52RHyp7gTGMrrHIuKK"
    "ehb4rMDNRMQu4DAwCFysHT2o36n/GrgKfM+bcxLbMh/5PcmPG/C1MxJbgaECt5jkQAPdwSQ3Z"
    "fjaTv4pYCXwXY2IBlMVwMYM9SwiptJZhcHcmk1ELKgbSGuXdZiPiEm1B/goozuV/oQhoKvALU"
    "XEo5asYf8BAucIcdLDC5MAAAAASUVORK5CYILAi2bw"
)
icon_app_empty_png = zlib.decompress(base64.b64decode(
    icon_app_empty_png_str.encode('utf-8')
))
icon_app_unknown_png_str = (
    "eJwBLQTS+4lQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxQvMcPv1NUAAAO6SURBVGje7d"
    "lbiFVVGAfwtcdpvMRMdjGrQbGwMgm6SFFJ0IUI7EJQvlVESEEURQWRBfnW7SGUIIJesiASISH"
    "sKhnVSFkDXSCsUMMug2VmTTdznF8va2i12uOcc+bsM2dg1svm7LO+b/3/e631fd/6rxCm2ugN"
    "l+I6FJMN+EJs8G97BYsmA/BuPIK/EvDD8fk3nsDsdgTegZvwfQJ8BPBj2J+8/wG3Ylq7gD8Hf"
    "f7b3sTpSZ+TsS7r8zkun0jgC7AWBxNQX2L5GJv6s4zIyziplcBn4T78moAYxCpMr8G+E7fgx8"
    "R+P1aju0rgRQyJO5OBh/A05jTg7xg8FX2MtG9xfdPDLk7Da9nUv40zm+B7EV7NfH+Ipc0AflS"
    "c2gOJ829wY7O/Eq7C9iz8rsP8Rpx14S7sTRz+hgcxs8JlOgP3xz2V7q+VteyvESdXYFv2JZ5H"
    "bwsDxQl4NkmC4uwsq8X4owz8c+iZgDDdhTXZJt9Ri+Gm2DmN7wO4GR0tAn81vkrGH8GytRbj1"
    "2PnzVifRYd+XFgh8FOxMRtzUxKl+uohsDHZE9tLsueCJgI/MhaBac30Ba6NddaLDRNIosPKLD"
    "r8jofGE5ViVr4NexK/P+OeNOokBN5riEDy35yYeQ9m2bPuvICL8Um2zkvj/rhnoKTPErybLas"
    "PcF4N/ufFIjBt7+OCQ9g0l0CWPXdmYXctjivpe3gs+P5M+u/GnWOdDSojkFWng1nWXoXpsQhc"
    "jl3J/3/ETdtT4xjVEUjs5uOFLHt+iq3ZDK3HiXX6rp5AYr80y+YpmUsa9DkqgaZn1qIo+kII5"
    "4YQVoQQ9oUQhkIId4cQzi6K4q1mj1dJaVAUxXAI4ZcQQk8IoTOEsKYoiqEqxqqytjk+8a+qQV"
    "pSnFXZpghMEZgiUJI3qoisrSRQxWAtDaNd8bkE10z0EsFlIYTz6yGwKz7nhhBeypXmFgJfiA0"
    "hhDdCCPPi6+9q1UBvyLT+A3gSR9cB4I7EvqMOux48ml2SDGAFZtXzBbrxcOboJ9yOzjoJTKuh"
    "f0eUbgYy1frxcelSoxwBt42lktVDIF6SbCmRUxY3c01ehI9LbmIWN0oAvfHjDGdyyrKqNlZHV"
    "CB2Z3dhq3FErXsAM0uOoXvj+fiwVkSI2SVC1J70gD4agRIhYCjOwrETEaNPiSrd/+THfAnhLL"
    "yT9d2MMya8HsGVce2mh/f+5PczmRi2I8qG7XODH+Xwe7HP6G0QD2BG21aHmFvyxUfuGXrDZGl"
    "RfuzH14eSDdudRFH1Ov8HJt27wO4eZDcAAAAASUVORK5CYIIGMfuH"
)
icon_app_unknown_png = zlib.decompress(base64.b64decode(
    icon_app_unknown_png_str.encode('utf-8')
))
icon_chat_hex_png_str = (
    "eJwBoANf/IlQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxQvKkmKHTkAAAMtSURBVGje7d"
    "lLiFxVEAbgOpOZvGBiiI+AIVFEJQ6CjxAxiiCIDGgCAXWhxCAicSPoIiA+Fu58LSQgiOgmURB"
    "npQg+UFAUjUZFUZQk+ACViK9gjIhJdD43p/F4mZnuO7kz3S1dm+6+/Z86/1+3Tt3uqoiBTW+4"
    "Atci9RvxM/Gcf+1FrO0H4qN4AH8W5Cfz61E8guW9SHwIN+FAQbxF+CEcKa7/iFuxoFfIr8fb/"
    "muv4twCcxYmKpjPMd5N4qdjF/4uSO3HdW0O9acVIS/gjPkkvhR34reCxGHch0UdrB/GNvxUrD"
    "+CHRidS+Ipl8Svi43/wuM4eRb+TsJj2UfLvsOWxssuzsHLlVv/Bs5vwPdavFTx/T4ubYL4inx"
    "rjxXOv8XWVpQwklNivIbf8bxmpLi2CV9Wyu8E1syG+AjuwMHC4e+4F0sq2O3Fhis6jHjr2XBD"
    "5bvFuCufqfJ83d3J+Wo5uRp7K5F4GqumwW8vsCs78H9agd8yDeZU7CyEwhe4qhMBZa7vwYY2+"
    "FtqClhU4K9vg70Iuwv8R1XM0BTrWhXgrYi4OKW0u0b2DdXM1hmrTUppT0RcEhGv5Et/1NnwcE"
    "ppsklCs8GnlETEoaYiNu8Cmr7l3Rag3wWkQQoNBPSggFTTX6P/xJoQsLp438lzY2ymqlLXhhs"
    "Q8GxEbIyIbyLiQAf4TyLi+YhYExHvdV1ASumziLiwBv5oRGzupRTqqg0EDAQMBPwPBeh3Aanf"
    "BSzMr+uwudsEcWVEbKizYOdMneZ5JF4dksBEJwsTbqz0+o/hUZw4D8SX4cHKkOT73L5ZWsfRK"
    "O6vOPoFt2F4DogP4eZMtuxaP4xlx+N4dZ4DlLa3oy5Z53usxzuVPV7DWJMRuhwfT3E+xo7D56"
    "ocnLKFuK/J4Ex1m7fih8osbAdOqOFnSR6SlE3cg7i97FjP5UFbnqeR5fDu50xgQZu1m6YYkuz"
    "CKd2o0WfnGVdpH+KyKbAX4M0K9nWc1/WnITbm3C1b8s/kArAST1SGgV/hmp6a4GNhnhX8WhlO"
    "HKp8vgeLe/a3SY74k5WIT+Kp6YYkvSpkHT7Au+2GJL0sIs11nv8D2ZET1HJiHQUAAAAASUVOR"
    "K5CYIKFebsO"
)
icon_chat_hex_png = zlib.decompress(base64.b64decode(
    icon_chat_hex_png_str.encode('utf-8')
))
icon_chat_round_png_str = (
    "eJwBrwRQ+4lQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxQvHx852RoAAAQ8SURBVGje7Z"
    "pbiJVVFMf/+8xMM1qjORGZ2o2cQcoeKuhBMjEJKS2HqMiKrJCgC1FZPlRIPRk9FEIEWUSRFUM"
    "X8qFSgvH2MkEQKTY0U1l2GYuaOoNnnCY7vx7cBxabc+bb35lz+YTWy9kfe+3/uu7b2kc6ycnV"
    "AgSYJekqSUslXSypW9KZkjol5STlJY1KGpY0KGmfpD3OudGmWQ7kgF7gQ+Bv0tNx4BNgLdDWa"
    "MXXAV9Podw/wAjwDTAE/Jxg5A/AA3U3BLgUGCijwCjwBnAnsKicIkArsNB7fCtwpAzOAWBpPR"
    "R3wMNlvPg5cAvQXgVmK3A9sCfA/Bd4BmiplfJtwLZAyCFgTQ0ddDVwMJDxEXDqdIE7/ESz9DI"
    "wsw5RbgOeBYpG1gAwu1rAFuB9AzYJrGvAInEDUDBydwEd1QA9Z0AmgFUNXOmWAHkj//W0AKtM"
    "KI8DNyeE/l5gZQr8lX5MW8K8mDBG3BUL3gn8ZAZuSuB/zPMVga4I/EXGObcl8N5n9MgD82IMe"
    "N4M2gvkIg0AOCsC/zzDf0cE/weGf1sS81xg3Oyml0QIWJ/SgHbDvzaC/2wzH4rAYtsfeneDpB"
    "m+/apz7kDK+Zer9WHSOTci6QXDv3Gqyfib8f75kXPGRmBeygjcHimjCxjzY44Bp5fz2LX+CCx"
    "JO51z3zfgeB7F74/d7/rPDkk3VTKgRG816H6Rhv9t076unAHL/W9R0qcZNGCfpIJvLyutjjmf"
    "Y6dJ6vGdg86537NmgHNuUtKA/+ySdIGNQI8B+6qBV9S0/IOm3WMNOMd0fJdhA7417XOtAZ2mI"
    "z8NJWL2gelcVKxus6xAe1ydSAlqo1eM4L/ILvEpZY2b9gxJavUfx8KOFNQnabWkw5J+ieDfL2"
    "m7T4HPUsqyN7SCNWDMdMxJlT/OHZR0WcrVpLfKFLK6jdkUsrvuhRkuxC007UPWgGGTv4szbID"
    "VbSg8MH1pDlnzs6Y5MNPc0I4ALlz2+iuci7JCKySV6k/9zjlCC1eYCOzOYAT6prwI+Zrn4Uo3"
    "nyYrP9+kT97WpXJmeStKesXsrk9kKACPm/R50zk3XsnS2cCfJgpLMuD9buP9ycSbIvCkybX9V"
    "VXFaqd8C7Db6LMlZlB7UPt/qYkGPG30GImukwJXBKX0R5qg/K2+1F5K5zVpAR4NavbrG6h8b+"
    "DAzdUCvWhAisCm0g5YR+Uf9PXYEvUlVQenAssBrwXvAx8Dc+ug+BzgnUDW9mpef0JgB2wOgP8"
    "CHgJOqdFKczfwayBjK9BaSw/daPaIEv0IbKgmIr7adj8wHGAWgHvqlZ8LgPcqvPnuAp4CrvEV"
    "6FwQxQW+5r8R2FHh2XUn0N2IVWI50B/xmF0AjkbwDQCrm7HRXA5sqfDmm0R/+AfDK6ejQ63+K"
    "+H8bWmZTvxXokfSGb5c4yQd1Yn/Sgz54tReSV/4A+T/dFLTf7LkV68GLfNrAAAAAElFTkSuQm"
    "CCYZwtSQ=="
)
icon_chat_round_png = zlib.decompress(base64.b64decode(
    icon_chat_round_png_str.encode('utf-8')
))
icon_download_png_str = (
    "eJwBNATL+4lQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxMOODPjbxcAAAPBSURBVGje7Z"
    "ltaNV1FMe/5zpNxU0pK1AUCc0HggyZLEMYRIz5ELGshuSSEH0j2YtATIkKxEoiBkEMfdMCy/U"
    "mEJdripKo4YoERTRYQqWVzplOVnvwfnrhb/jzx72793/3v3f3ws6by/3fc77/7/k9nHPuOdKY"
    "pBfgWWANYKVGfC7wDfekFVhQCsTLgQ+A/zzySffZD3wCTCtG4glgPXDFIz5E+COgz3t+FdgEj"
    "CsW8pXACe6XduAJT2ce0BLonAdqRpP4HKAZuOOR+gV4KcOlPhs4cgB4rJDEJwNbgVseiR7gXe"
    "CBLOzLgI3ANc++D2gEyvNJ3FxIvOS9eBBoAh7OAW868JnDGJI/gFdjD7vAQuBQsPXHgMUxYC8"
    "Avg2wO4Bn4iD+oNvaAQ/8d6Ah7lUCVgOdQfhtAWbnAjYeeBPo9gBvAzuASXk8phOBbe5O+ffr"
    "7XT3y1KArJT0saT5Q48k7ZO01cwuZ8oHklZISufkv5JazSyZAWeGpF2S1nkcOyW9YWatmVbBP"
    "+ungacjrGAtmWVlBLylwCnP9udQJzHMrhyXVGVmpyKcgikx6dwlYnZa0jJJbe5RbzYODElPpq"
    "0uhJgZkm6m+z1R6iV7qTlAqTtgY0dozIExB+6XshxrljJXMoT1SVUW5lVAmF/6XIkxGEdB1eb"
    "S9sFhdOqJX9YO8779TudEXEeo3RVXccklSd8V7A6Y2XVJNZK6YiDfI+l5M+sq6CU2s05JdZL6"
    "R0B+UFKdmZ0blShkZsclveZSPDmUBJvN7PCohlEz+0rS+y7NZ+uESdppZk3Fkgfek9ScqlZJI"
    "19LeqdoEpmr2TdIOpKFeoek9XH910hkU7Jm6cSApJclXcwQLleZWW8+SwkbwU50S6qVdC3Fzz"
    "ck1ZrZ1fz+Y4CjLuv9BbyQI8ayoMXeD1TniPUc8Fu6TJzK4PPhOs0RXvyKa04lgYYc7MMhCUB"
    "LNoYGrAt6/QPAp8BDEUm8CNRHtKkAPgx28E9gAzA5ClA5sCsAug5sdtVo3Ec3AbzuyPpd691A"
    "xUiAZ7k5gC8XgBUxkq8ETgbvOAwsinOFqoEzKe7HohFgznSLk/QwL8a5OKm2uQH4O4gwjcDUC"
    "DiT3JDEb+J2A1uA8flvzsA0N430h3ddjsC4DLarUwxJmoFHCt9lgsfdjMuXn4DlKXSfAr4PdI"
    "8CT45+uwxWubPrDye+dAHgUWBPMAz81YXY4pngAxOAt4B/guHEzeD7dmBi0bY53IrvDVY8CXw"
    "BzCyZfg2wBPgR+CHKkKTYnLB8n/P/ASEng6fsVypOAAAAAElFTkSuQmCC783vNQ=="
)
icon_download_png = zlib.decompress(base64.b64decode(
    icon_download_png_str.encode('utf-8')
))
icon_library_png_str = (
    "eJwBGAXn+olQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAZiS0dEAAAAAAAA+"
    "UO7fwAAAAlwSFlzAAAHYQAAB2EBlcO4tgAAAAd0SU1FB+gCCxQwC8i5A/kAAASlSURBVGje7Z"
    "lbiJVVFMf/a2YcRRvzEpki4iV1lLRUMqKMyEtmSkkNBZXVQwoViCCIPVR0IYMooiKkekgfIos"
    "u1JiiloVRoaVReUNJoywv4JSXwdGZXy/ro9XmjHPmzJkzZ6j18p1v7/9ee/33XmvtfdYn/S+5"
    "BTBgEXA7YN2RwDz+kbVAbXcjMBloCiSagBeAfuVq8BLgAPAo0NfbLgWeA84EIkfctSrLjcDeY"
    "OQ+4A6gyvtGA2v4t+wEbuxKg68CxoX3BcBviZGbgMkBMx34IcF8BIwstfHXAi1AI/A0cIG3Vw"
    "ELgaPBwLPAKuCS82DOAC8CNaUiMCtZxV+Bu7N0CQxwg84GzDFgGdDLMRcBrwLnWtNTTINvBt7"
    "z1FjpbfOBTxMiXwFTw7ha4JMcvn9LG5itwDXFJLDbFTcD9cCEJN/vD5O3eMAOawOzNomhNvV0"
    "hMAzrjCT08DzwEDvrwYWA38GzEng8eAyuTCnHdPHMb2A5cCJgDkBPAL0zNfY+4E97jI1oX0Y8"
    "GZC5BDwANDDMUNyYPYD84OewcBK3814NiwGKs6jZx8wJx8Cm8OgP/zQqQr9U4Atic9uA2a1gf"
    "kMuLwNzBdJ2p3qcZXJ9nwIpHka4KfI3i9qdcDBgGkG3gFGJJgDCWYVcHHA3OPZJ2LeAAYFzDr"
    "v+zIfAusdfDgHkU3ApIDt7T7cmPj+inA25MIc95Ta0zF9gKcSTEO2Y8DbhRCoB2YAOxISWXYY"
    "HsYM9ZVNffa24NcjgHdzpNTZQc9wj71M5nWIgL9X+DXhUDL5KV/pvmHs9TkIfw1c2QbmQ2CU9"
    "48PCzEzIbCl3QQSd1kG/JVMftQzSFVC+HDi1yuB/o6p9ORwJCaCQCCTGR3egRz9Q9yYcwmRXU"
    "BdwPX3+39Tcp14MJzm/YBvonHtJVDR3kPNzA6Z2SJJEyR9HLpqJa0BNgKTzOy4mS2RNFHSOsc"
    "MlPSKpO+AoWbWIOlgxrmQQ7ai0NPZzHaZ2TxJMyV9H7qmS9qWBbqZ7TazmyTNlbTXMRMljSvG"
    "NaeiowrMbKOkKZIWSvo96K2TtAd4C6g0s3pJcyS1OKYxH/WdTsBJNJvZa5LGSHpC0invqpZ0p"
    "6Srg5sUZc6iEghETprZY04kJoFzhaosKYEY6JKWhqaWQowr+Q4Ue3XLiUCnVea6koCVbQyUcu"
    "fKncB/M4jp7kFsZRTEBRGo9ucU4NYudqGz/hzcHgK/+HOQpPeBDcBlXeRC2Qne4M+T+RC4T9K"
    "CcLOcIWk78HJWyCphcGcE7pI035/nJ2BmmNlqSWMlrZB0RlKVpIck7QUejnWiTpCx4Xez23TC"
    "zD4ws2N5p1EftFzSaEmrvXmApJck/ZhXlaywIP5c0lZJOyX9XMwCb65qwgZgfCv42oCb5m0jc"
    "/zfXZ93xaEjB5mZbZY0WdK9ko6E+Njh3wIuLHBtaqK7lES8mrAi+Xh3zMsrlXnuQFbzGQ08CV"
    "xR8rsAMMa/cUX5FpjWCoHZqQuVhQBzvSQfy4/14f06x43ymmdja7HTlSSqgaVuYCqxsl2TVej"
    "KUoBBwOtJoffZbndPd7dq8rroDd3yzwbQA+jdmXP8DYifG1zLVTIZAAAAAElFTkSuQmCCxThq"
    "SQ=="
)
icon_library_png = zlib.decompress(base64.b64decode(
    icon_library_png_str.encode('utf-8')
))
